% Define UzL colors
uzl_green = [0, 75, 90] / 256;
uzl_gray = [166, 166, 166] / 256;
uzl_orange = [236, 116, 4] / 256;
uzl_skyblue = [110, 165, 206] / 256;
uzl_blue = [0, 106, 163] / 256;
uzl_red = [181, 22, 33] / 256;
uzl_lightgreen = [149, 188, 14] / 256;

uzl_map = [uzl_green; uzl_orange; uzl_skyblue; uzl_red; uzl_lightgreen; uzl_blue; uzl_gray];

set(groot, 'defaultAxesColorOrder', uzl_map, ...
           'DefaultAxesXGrid', 'on', ...
           'DefaultAxesYGrid', 'on', ...
           'DefaultAxesFontWeight', 'normal', ...
           'DefaultAxesFontSize', 12, ...
           'DefaultAxesTitleFontWeight', 'normal', ...
           'DefaultAxesTitleFontSizeMultiplier', 1, ...
           'DefaultTextFontName', 'Cambria', ...
           'DefaultLineLineWidth', 2) ;
       
 % Prevent plots from annoying popping up in foreground
 set(groot, 'DefaultFigureWindowState', 'minimized');